# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/bank/user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from proto.bank import account_pb2 as proto_dot_bank_dot_account__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/bank/user.proto\x12\x04\x62\x61nk\x1a\x19google/protobuf/any.proto\x1a\x18proto/bank/account.proto\"Y\n\x04User\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x1e\n\x07\x61\x63\x63ount\x18\x04 \x01(\x0b\x32\r.bank.Account\"\'\n\x0bUserRequest\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.bank.User\"\x1e\n\x0cUserResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2>\n\x0bUserService\x12/\n\x04User\x12\x11.bank.UserRequest\x1a\x12.bank.UserResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.bank.user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=84
  _USER._serialized_end=173
  _USERREQUEST._serialized_start=175
  _USERREQUEST._serialized_end=214
  _USERRESPONSE._serialized_start=216
  _USERRESPONSE._serialized_end=246
  _USERSERVICE._serialized_start=248
  _USERSERVICE._serialized_end=310
# @@protoc_insertion_point(module_scope)
