# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.bank import user_pb2 as proto_dot_bank_dot_user__pb2


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UserDetails = channel.unary_unary(
                '/bank.UserService/UserDetails',
                request_serializer=proto_dot_bank_dot_user__pb2.UserRequest.SerializeToString,
                response_deserializer=proto_dot_bank_dot_user__pb2.UserResponse.FromString,
                )
        self.Withdrawal = channel.unary_unary(
                '/bank.UserService/Withdrawal',
                request_serializer=proto_dot_bank_dot_user__pb2.WithdrawalRequest.SerializeToString,
                response_deserializer=proto_dot_bank_dot_user__pb2.WithdrawalResponse.FromString,
                )


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UserDetails(self, request, context):
        """Unary communication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Withdrawal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UserDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.UserDetails,
                    request_deserializer=proto_dot_bank_dot_user__pb2.UserRequest.FromString,
                    response_serializer=proto_dot_bank_dot_user__pb2.UserResponse.SerializeToString,
            ),
            'Withdrawal': grpc.unary_unary_rpc_method_handler(
                    servicer.Withdrawal,
                    request_deserializer=proto_dot_bank_dot_user__pb2.WithdrawalRequest.FromString,
                    response_serializer=proto_dot_bank_dot_user__pb2.WithdrawalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bank.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UserDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bank.UserService/UserDetails',
            proto_dot_bank_dot_user__pb2.UserRequest.SerializeToString,
            proto_dot_bank_dot_user__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Withdrawal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bank.UserService/Withdrawal',
            proto_dot_bank_dot_user__pb2.WithdrawalRequest.SerializeToString,
            proto_dot_bank_dot_user__pb2.WithdrawalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
